version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      # Required for bot operation
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      # Optional: for guild-specific command registration
      GUILD_ID: ${GUILD_ID}
    # Uncomment if you want to see logs interactively
    # tty: true
    # stdin_open: true
